### ISSUE TITLE
remove migration guides as a specific category from Bevy Assets

### ISSUE THREAD

**Issue by mockersf** [bevyengine/bevy-assets#112]
Now that Bevy Assets are deployed as part of the website, it's a little strange to have the migration guides take so much space: https://bevyengine.org/assets/#migration-guides when they are also https://bevyengine.org/learn/book/migration-guides/. I think it makes sense to keep them as a separate category if we plan to rely on community for migration guides, but not if they are officials

Proposal:
- Remove individual official migration guides from Bevy Asset
- Move the unofficial migration guide to the `Learning/Tutorials` category
- Remove the `Learning/Migration Guides` category
- (maybe) Add an assets to `Learning/Tutorials` for general migration guides linking to https://bevyengine.org/learn/book/migration-guides/
- (maybe) Remove the subcategory `Tutorials` from `Learning`. This would need an evolution on Bevy Assets website to allow assets on parent category

**Comment by cart** [comment]
The whole proposal sounds good to me (including the maybes). I think ultimately we'll want more Learning categories (including one for tutorials), but the problem is that almost everything in "learning' is a tutorial, so adding something like a "physics" category would create a situation where someone needs to choose either "tutorial" _or_ "physics". I'm down to just consolidate everything under Learning until we support multiple "category tags" for assets.
