### ISSUE TITLE
Sort assets by most recently supported Bevy version

### ISSUE THREAD

**Issue by ItsDoot** [bevyengine/bevy-assets#297]
As the Assets page grows, it becomes notably harder to sort through the assets that are actually usable with a recent or current Bevy version. IMO, the page would be well suited to sorting by assets which have been more recently updated to the current Bevy version. Especially when there are Assets among them which only work on very old Bevy versions.

**Comment by doonv** [comment]
This would require making everyone add a `version` key to their toml. Which will be a lot of work, but it will be possible

**Comment by alice-i-cecile** [comment]
We can also sort assets without a version to the bottom.

**Comment by doonv** [comment]
> We can also sort assets without a version to the bottom.

We should still make some kind of announcement when we implement the version sorting so that the assets get updated with the correct version.

**Comment by james7132** [comment]
I'm running into this with `bevy_system_graph`, which is now deprecated as a whole, due to the changes in Schedule V3. I don't want to remove it from here because it may still be usable for older versions of the engine, but it's not being maintained or updated anymore from engine release to release.
